spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zwgl?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update  # ??????????
    show-sql: false      # ?? SQL ??
    properties:
      hibernate:
        format_sql: true # ??? SQL ??
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  web:
    resources:
      static-locations: classpath:/static/, file:uploads/

server:
  port: 8080  # ??????

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG

